### ISSUE TITLE
Error installing rails: Failed to build gem native extension.

### ISSUE THREAD

**Issue by agustin-rios** [IIC2143-2020-2/syllabus#82]
Me tira el siguiente error al querer instalar rails:

```
Building native extensions. This could take a while...
ERROR:  Error installing rails:
        ERROR: Failed to build gem native extension.

    current directory: /home/arios6/.rvm/gems/ruby-2.7.0/gems/nokogiri-1.10.10/ext/nokogiri
/home/arios6/.rvm/rubies/ruby-2.7.0/bin/ruby -I /home/arios6/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0 -r ./siteconf20200828-14358-p450x4.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/arios6/.rvm/rubies/ruby-2.7.0/bin/$(RUBY_BASE_NAME)
        --help
        --clean
/home/arios6/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /home/arios6/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/mkmf.rb:597:in `block in try_compile'
        from /home/arios6/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/mkmf.rb:544:in `with_werror'
        from /home/arios6/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/mkmf.rb:597:in `try_compile'
        from extconf.rb:138:in `nokogiri_try_compile'
        from extconf.rb:162:in `block in add_cflags'
        from /home/arios6/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/mkmf.rb:655:in `with_cflags'
        from extconf.rb:161:in `add_cflags'
        from extconf.rb:416:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/arios6/.rvm/gems/ruby-2.7.0/extensions/x86_64-linux/2.7.0/nokogiri-1.10.10/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/arios6/.rvm/gems/ruby-2.7.0/gems/nokogiri-1.10.10 for inspection.
Results logged to /home/arios6/.rvm/gems/ruby-2.7.0/extensions/x86_64-linux/2.7.0/nokogiri-1.10.10/gem_make.out
```

Que puedo hacer?

**Comment by Gaonuk** [comment]
En que sistema operativo estas?

**Comment by agustin-rios** [comment]
Estoy usando WSL2, lamentablemente eso no funciono

**Comment by daleal** [comment]
Me podrías decir cual es tu _output_ al ejecutar `rvm requirements`?

**Comment by agustin-rios** [comment]
Ya no importa, gracias! logre instalarlo al desinstalar todo y pasando de ubuntu 20 lts al normal
